# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bloque_servicio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bloque_servicio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62loque_servicio.proto\x12\x05\x64\x66sha\"q\n\x15\x45scribirBloqueRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x10\n\x08posicion\x18\x03 \x01(\x05\x12\x11\n\tcontenido\x18\x04 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\t\"J\n\x16\x45scribirBloqueResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x10\n\x08\x62lock_id\x18\x03 \x01(\t\"%\n\x11LeerBloqueRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"\x8e\x01\n\x12LeerBloqueResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x10\n\x08\x62lock_id\x18\x03 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x04 \x01(\t\x12\x10\n\x08posicion\x18\x05 \x01(\x05\x12\x11\n\tcontenido\x18\x06 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x07 \x01(\t\")\n\x15\x45liminarBloqueRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"8\n\x16\x45liminarBloqueResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xf1\x01\n\x0e\x42loqueServicio\x12M\n\x0e\x45scribirBloque\x12\x1c.dfsha.EscribirBloqueRequest\x1a\x1d.dfsha.EscribirBloqueResponse\x12\x41\n\nLeerBloque\x12\x18.dfsha.LeerBloqueRequest\x1a\x19.dfsha.LeerBloqueResponse\x12M\n\x0e\x45liminarBloque\x12\x1c.dfsha.EliminarBloqueRequest\x1a\x1d.dfsha.EliminarBloqueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bloque_servicio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESCRIBIRBLOQUEREQUEST']._serialized_start=32
  _globals['_ESCRIBIRBLOQUEREQUEST']._serialized_end=145
  _globals['_ESCRIBIRBLOQUERESPONSE']._serialized_start=147
  _globals['_ESCRIBIRBLOQUERESPONSE']._serialized_end=221
  _globals['_LEERBLOQUEREQUEST']._serialized_start=223
  _globals['_LEERBLOQUEREQUEST']._serialized_end=260
  _globals['_LEERBLOQUERESPONSE']._serialized_start=263
  _globals['_LEERBLOQUERESPONSE']._serialized_end=405
  _globals['_ELIMINARBLOQUEREQUEST']._serialized_start=407
  _globals['_ELIMINARBLOQUEREQUEST']._serialized_end=448
  _globals['_ELIMINARBLOQUERESPONSE']._serialized_start=450
  _globals['_ELIMINARBLOQUERESPONSE']._serialized_end=506
  _globals['_BLOQUESERVICIO']._serialized_start=509
  _globals['_BLOQUESERVICIO']._serialized_end=750
# @@protoc_insertion_point(module_scope)
