# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Proto import bloque_servicio_pb2 as bloque__servicio__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bloque_servicio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BloqueServicioStub:
    """Aqui se define el servicio gRPC encargado de las operaciones sobre bloques, la logoca pero no se si esta buena

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EscribirBloque = channel.unary_unary(
                '/dfsha.BloqueServicio/EscribirBloque',
                request_serializer=bloque__servicio__pb2.EscribirBloqueRequest.SerializeToString,
                response_deserializer=bloque__servicio__pb2.EscribirBloqueResponse.FromString,
                _registered_method=True)
        self.LeerBloque = channel.unary_unary(
                '/dfsha.BloqueServicio/LeerBloque',
                request_serializer=bloque__servicio__pb2.LeerBloqueRequest.SerializeToString,
                response_deserializer=bloque__servicio__pb2.LeerBloqueResponse.FromString,
                _registered_method=True)
        self.EliminarBloque = channel.unary_unary(
                '/dfsha.BloqueServicio/EliminarBloque',
                request_serializer=bloque__servicio__pb2.EliminarBloqueRequest.SerializeToString,
                response_deserializer=bloque__servicio__pb2.EliminarBloqueResponse.FromString,
                _registered_method=True)


class BloqueServicioServicer:
    """Aqui se define el servicio gRPC encargado de las operaciones sobre bloques, la logoca pero no se si esta buena

    """

    def EscribirBloque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeerBloque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarBloque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BloqueServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EscribirBloque': grpc.unary_unary_rpc_method_handler(
                    servicer.EscribirBloque,
                    request_deserializer=bloque__servicio__pb2.EscribirBloqueRequest.FromString,
                    response_serializer=bloque__servicio__pb2.EscribirBloqueResponse.SerializeToString,
            ),
            'LeerBloque': grpc.unary_unary_rpc_method_handler(
                    servicer.LeerBloque,
                    request_deserializer=bloque__servicio__pb2.LeerBloqueRequest.FromString,
                    response_serializer=bloque__servicio__pb2.LeerBloqueResponse.SerializeToString,
            ),
            'EliminarBloque': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarBloque,
                    request_deserializer=bloque__servicio__pb2.EliminarBloqueRequest.FromString,
                    response_serializer=bloque__servicio__pb2.EliminarBloqueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfsha.BloqueServicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfsha.BloqueServicio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BloqueServicio:
    """Aqui se define el servicio gRPC encargado de las operaciones sobre bloques, la logoca pero no se si esta buena

    """

    @staticmethod
    def EscribirBloque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.BloqueServicio/EscribirBloque',
            bloque__servicio__pb2.EscribirBloqueRequest.SerializeToString,
            bloque__servicio__pb2.EscribirBloqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeerBloque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.BloqueServicio/LeerBloque',
            bloque__servicio__pb2.LeerBloqueRequest.SerializeToString,
            bloque__servicio__pb2.LeerBloqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarBloque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfsha.BloqueServicio/EliminarBloque',
            bloque__servicio__pb2.EliminarBloqueRequest.SerializeToString,
            bloque__servicio__pb2.EliminarBloqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
